services:
  # -----------------------------
  # PostgreSQL Database
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: swiftlog_user
      POSTGRES_PASSWORD: swiftlog_pass
      POSTGRES_DB: swiftlog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admins
    ports:
      - "5050:80"

  # -----------------------------
  # RabbitMQ - Event Bus
  # -----------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # -----------------------------
  # API Gateway
  # -----------------------------
  api-gateway:
    build: ./backend/services/api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - auth-service
      - order-service
    volumes:
      - ./backend/services/api-gateway/app:/app/app
    command: [ "uvicorn", "app.gateway_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - ORDER_SERVICE_URL=http://order-service:8002

  # -----------------------------
  # Authentication Service
  # -----------------------------
  auth-service:
    build: ./backend/services/auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend/services/auth-service/app:/app/app
    command: [ "uvicorn", "app.auth_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Admin Service
  # -----------------------------
  admin-service:
    build: ./backend/services/admin-service
    container_name: admin-service
    ports:
      - "8003:8000"
    depends_on:
      - auth-service
      - cms-mock
      - postgres
    volumes:
      - ./backend/services/admin-service/app:/app/app
    command: [ "uvicorn", "app.admin_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - CMS_URL=http://cms-mock:8200
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Order Service
  # -----------------------------
  order-service:
    build: ./backend/services/order-service
    container_name: order-service
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
      - cms-mock
      - ros-mock
      - wms-mock
      - postgres
    volumes:
      - ./backend/services/order-service/app:/app/app
    command: [ "uvicorn", "app.order_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - CMS_URL=http://cms-mock:8200
      - ROS_URL=http://ros-mock:8100
      - WMS_HOST=wms-mock
      - WMS_PORT=8300
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Tracking Service
  # -----------------------------
  tracking-service:
    build: ./backend/services/tracking-service
    container_name: tracking-service
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./backend/services/tracking-service/app:/app/app
    command: [ "uvicorn", "app.tracking_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Notification Service
  # -----------------------------
  notification-service:
    build: ./backend/services/notification-service
    container_name: notification-service
    ports:
      - "8005:8000"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./backend/services/notification-service/app:/app/app
    command: [ "uvicorn", "app.notification_app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Driver Service
  # -----------------------------
  driver-service:
    build: ./backend/services/driver-service
    container_name: driver-service
    ports:
      - "8006:8000"
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./backend/services/driver-service/app:/app/app
    command: [ "uvicorn", "app.driver:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Mock Systems
  # -----------------------------
  cms-mock:
    build: ./backend/services/mock_systems/cms
    container_name: cms-mock
    ports:
      - "8200:8200"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  ros-mock:
    build: ./backend/services/mock_systems/ros
    container_name: ros-mock
    ports:
      - "8100:8100"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db
  wms-mock:
    build: ./backend/services/mock_systems/wms
    container_name: wms-mock
    ports:
      - "8300:8300"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Adapters
  # -----------------------------
  cms-adapter:
    build: ./backend/services/adapters/cms_adapter
    container_name: cms-adapter
    ports:
      - "8201:8000"
    depends_on:
      - cms-mock
    volumes:
      - ./backend/services/adapters/cms_adapter/app:/app/app
    command: [ "uvicorn", "app.cms_adapter:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - CMS_URL=http://cms-mock:8200

  ros-adapter:
    build: ./backend/services/adapters/ros_adapter
    container_name: ros-adapter
    ports:
      - "8101:8000"
    depends_on:
      - ros-mock
      - rabbitmq
    volumes:
      - ./backend/services/adapters/ros_adapter/app:/app/app
    command: [ "python", "-u", "app/ros_adapter.py" ]
    environment:
      - ROS_URL=http://ros-mock:8100
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  wms-adapter:
    build: ./backend/services/adapters/wms_adapter
    container_name: wms-adapter
    ports:
      - "8301:8000"
    depends_on:
      - wms-mock
      - rabbitmq
    volumes:
      - ./backend/services/adapters/wms_adapter/app:/app/app
    command: [ "python", "-u", "app/wms_adapter.py" ]
    environment:
      - WMS_URL=http://wms-mock:8300
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

volumes:
  postgres_data:
