services:
  # -----------------------------
  # PostgreSQL Database
  # -----------------------------
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: swiftlog_user
      POSTGRES_PASSWORD: swiftlog_pass
      POSTGRES_DB: swiftlog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admins
    ports:
      - "5050:80"

  # -----------------------------
  # RabbitMQ - Event Bus
  # -----------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # -----------------------------
  # API Gateway
  # -----------------------------
  api-gateway:
    build: ./backend/services/api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - auth-service
      - order-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - ORDER_SERVICE_URL=http://order-service:8002

  # -----------------------------
  # Authentication Service
  # -----------------------------
  auth-service:
    build: ./backend/services/auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Admin Service
  # -----------------------------
  admin-service:
    build: ./backend/services/admin-service
    container_name: admin-service
    ports:
      - "8003:8000"
    depends_on:
      - auth-service
      - cms-mock
      - postgres
    environment:
      - CMS_URL=http://cms-mock:8200
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  # -----------------------------
  # Order Service
  # -----------------------------
  order-service:
    build: ./backend/services/order-service
    container_name: order-service
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
      - cms-mock
      - ros-mock
      - wms-mock
      - postgres
    environment:
      # - RABBITMQ_HOST=rabbitmq
      # - RABBITMQ_PORT=5672
      # - CMS_URL=http://cms-mock:8200
      # - ROS_URL=http://ros-mock:8100
      # - WMS_HOST=wms-mock
      # - WMS_PORT=8300
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5433/swiftlog_db

  # -----------------------------
  # Tracking Service
  # -----------------------------
  tracking-service:
    build: ./backend/services/tracking-service
    container_name: tracking-service
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5433/swiftlog_db

  # -----------------------------
  # Notification Service
  # -----------------------------
  notification-service:
    build: ./backend/services/notification-service
    container_name: notification-service
    ports:
      - "8005:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5433/swiftlog_db

  # -----------------------------
  # Mock Systems
  # -----------------------------
  cms-mock:
    build: ./backend/services/mock_systems/cms
    container_name: cms-mock
    ports:
      - "8200:8200"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

  ros-mock:
    build: ./backend/services/mock_systems/ros
    container_name: ros-mock
    ports:
      - "8100:8100"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db
  wms-mock:
    build: ./backend/services/mock_systems/wms
    container_name: wms-mock
    ports:
      - "8300:8300"
    environment:
      - DATABASE_URL=postgresql+asyncpg://swiftlog_user:swiftlog_pass@postgres:5432/swiftlog_db

volumes:
  postgres_data:
